# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - artwork-service-container

on:
  push:
    branches:
      - docker
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://yanayartwork.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3e0ca63b151b4b0694a67297379ffd45 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7762519615d947759b921527a733facb }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: yanayartwork.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3e0ca63b151b4b0694a67297379ffd45 }}/artwork-service:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'artwork-service-container'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_25aa0045f8be4ad7b47805b26c66ad6e }}
        images: 'yanayartwork.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3e0ca63b151b4b0694a67297379ffd45 }}/artwork-service:${{ github.sha }}'