# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - artwork-service-container

on:
  push:
    branches:
      - dockerize
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_72a7bd2452a342fbbf6707c37f41e4cf }}
        password: ${{ secrets.AzureAppService_ContainerPassword_45c7a9eaaf8d44758ec05500ede785fa }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_72a7bd2452a342fbbf6707c37f41e4cf }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'artwork-service-container'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fbed82ea02a543d4bd53a62ee41ffbfb }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_72a7bd2452a342fbbf6707c37f41e4cf }}/appsvc/staticsite:${{ github.sha }}'